### ISSUE TITLE
Crash app when download reel from fb as well as Instagram 

### ISSUE THREAD

**Issue by arehmaan006** [Udhayarajan/VidSnap#21] opened 2023-02-08 20:26 UTC
Bro app crash  when download reel from from fb amd inst....On android studio logcat show error in extractor activity. Can you please resolve it..
Thanks

**Comment by arehmaan006** [comment] 2023-02-08 21:31
![Screenshot_20230209_023125_VidSnap](https://user-images.githubusercontent.com/89921312/217655612-498209ef-d749-4e16-867a-906a74529cd6.jpg)

**Comment by Udhayarajan** [comment] 2023-02-09 09:44
If you don't mind, Could you please share the reel link ?

**Comment by arehmaan006** [comment] 2023-02-09 09:51
Bro almost all links when i paste on url textfield it's says error
sometimes it crashed. Also crash on fb video downloading. I sharing some
links for better experience thanks you

https://www.facebook.com/1712347125475907/posts/pfbid0s7BKkZiRWGeFWVdConLYHHcAVhGrd93GsE6kcNkBVr4oJ8r6BKcjvs4kCRgnNxhXl/?mibextid=Nif5oz

https://www.facebook.com/reel/905763867116775?s=yWDuG2&fs=e&mibextid=Nif5oz

https://www.facebook.com/reel/1103184483655777?s=yWDuG2&fs=e&mibextid=Nif5oz

https://www.instagram.com/reel/CmM6oj9gpgP/?igshid=YmMyMTA2M2Y=

https://www.instagram.com/reel/Cn_1I3jjegT/?igshid=YmMyMTA2M2Y=

**Comment by Udhayarajan** [comment] 2023-02-20 20:02
Your issue is addressed in latest version v5.0.2-beta. If you find out still the problem is not solved yet, you're welcome to reopen this again. Thanks for your time on reporting such critical bug

**Closed by Udhayarajan** 2023-02-20 20:02 UTC

**Comment by arehmaan006** [comment] 2023-02-20 20:13
Thank you soo much bro.really appreciate it❤
