### ISSUE TITLE
Download Location in SettingFragment does not work!

### ISSUE THREAD

**Issue by NanyangTaiji** [Udhayarajan/VidSnap#23] opened 2023-03-27 04:05 UTC
1. if your first activity after installation is SettingFragment, it will crash after Download location selection.
2. Regardless whether you choose the default and change the directory, the fragment will not update the outcome.
3. Essentially, it does not work at all. But the location is able to change in other fragments.

**Comment by Udhayarajan** [comment] 2023-03-27 05:07
I would like to know additional details about that particular error.

In what version of APK you're experiencing it?
If possible can you provide me with the log details of the error?

**Comment by NanyangTaiji** [comment] 2023-03-30 04:21
I guess the reason is that your storage permissions are requested in the first downloading. then problem occurs when  your first action after installation is to set Download path in SettingFragment directly.

**Comment by Udhayarajan** [comment] 2023-05-19 19:11
I can't reproduce the problem could you please suggest to me step by step what you have followed to get the crash?

**Comment by Udhayarajan** [comment] 2023-07-27 19:10
Closing this as it does not have proper information

**Closed by Udhayarajan** 2023-07-27 19:10 UTC
Labels: question
