### ISSUE TITLE
Not downloading instagram content many times, after one two downloads its saying something went wrong, and after certain hours it is back

### ISSUE THREAD

**Issue by amit8899** [Udhayarajan/VidSnap#9] opened 2022-02-21 11:31 UTC

**Comment by Udhayarajan** [comment] 2022-02-28 04:39
Yeah i have noticed this issue and it will be solved as soon as possible thanks for letting me know. This issue is duplicate of  #7

**Closed by Udhayarajan** 2022-02-28 04:39 UTC
